kind: Pod
apiVersion: v1
metadata:
  name: pod2-app
  labels:
    app: pod2
spec:
  containers:
    - name: pod2-app
      image: hashicorp/http-echo
      args:
        - "-text=pod2"

---

kind: Service
apiVersion: v1
metadata:
  name: pod2-service
spec:
  selector:
    app: pod2
  ports:
    - port: 5678
